describe('Add to cart', () => {
  it('login, add to cart, shopping cart badge', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('standard_user')
    cy.get('#password').type('secret_sauce')
    cy.get('#login-button').click()
    cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
    cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
    cy.get('.shopping_cart_badge').should('have.text', '3')
  })
    it('login, add to cart, shopping cart link', () => {
      cy.visit('https://www.saucedemo.com/')
      cy.get('#user-name').type('standard_user')
      cy.get('#password').type('secret_sauce')
      cy.get('#login-button').click()
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
      cy.get('.shopping_cart_link').click()
      cy.get('.cart_item').should('have.length', 3)
})
    it('remove product from cart', () => {
      cy.visit('https://www.saucedemo.com/')
      cy.get('#user-name').type('standard_user')
      cy.get('#password').type('secret_sauce')
      cy.get('#login-button').click()
      cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
      cy.get('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click()
      cy.get('.shopping_cart_link').click()
      cy.get('.cart_item').should('have.length', 3)
      cy.get('[data-test="remove-sauce-labs-backpack"]').click()
      cy.get('.cart_item').should('have.length',2)
})
it('remove the product using the remove button', () => {
  cy.visit('https://www.saucedemo.com/')
  cy.get('#user-name').type('standard_user')
  cy.get('#password').type('secret_sauce')
  cy.get('#login-button').click()
  cy.get('[data-test="add-to-cart-sauce-labs-backpack"]').click()
  cy.get('[data-test="add-to-cart-sauce-labs-bike-light"]').click()
  cy.get('.shopping_cart_badge').should('have.text', '2')
  cy.get('[data-test="remove-sauce-labs-backpack"]').click()
  cy.get('.shopping_cart_badge').should('have.text', '1')
})
})