describe('Login', () => {
  it('correct_login', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('standard_user')
    cy.get('#password').type('secret_sauce')
    cy.get('#login-button').click()
    cy.url().should('include', 'https://www.saucedemo.com/inventory.html')
  })
  it('wrong_login', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('wrong')
    cy.get('#password').type('wrong')
    cy.get('#login-button').click()
    cy.get('[data-test="error"]')
    .should('be.visible')
    .and('contain', 'Epic sadface: Username and password do not match any user in this service')
  })
  it('empty_fields', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#login-button').click()
    cy.get('[data-test="error"]')
      .should('be.visible')
      .and('contain', 'Username is required')
  })
  it('missing_password', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('standard_user')
    cy.get('#login-button').click()
    cy.get('[data-test="error"]')
      .should('be.visible')
      .and('contain', 'Password is required')
  })
  it('locked_out_user', () => {
    cy.visit('https://www.saucedemo.com/')
    cy.get('#user-name').type('locked_out_user')
    cy.get('#password').type('secret_sauce')
    cy.get('#login-button').click()
    cy.get('[data-test="error"]')
      .should('be.visible')
      .and('contain', 'Epic sadface: Sorry, this user has been locked out.')
  })
})